### ISSUE TITLE
How can I use this in a test?

### ISSUE THREAD

**Issue by Kjerno** [quarkiverse/quarkus-reactive-h2-client#49]
Hey hey!

I'm trying to implement this for a testsuite my team wrote using Quarkus. However, I'm not sure how to configure it.  Could you perhaps help?

`@QuarkusTest
public class StuffIntegrationTest {

    @Inject
    public DataSource dataSource;`
    
    `quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost:9092/mem:test;DB_CLOSE_DELAY=-1;init=runscript from 'classpath:schema.sql'
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.jdbc.initial-size=50
quarkus.datasource.jdbc.max-size=100`

Already tried replacing jdbc with reactive but that also didn't fixed.
Another try looked like:

`    @BeforeEach
    @RunOnVertxContext
    public void beforeEach(TransactionalUniAsserter asserter) throws SQLException {
        final var truncateEntityTabel = "TRUNCATE TABLE ENTITY RESTART IDENTITY;\n";
        asserter.execute(() -> dataSource.getConnection().map(val -> val.preparedQuery(truncateEntityTabel).execute()));
        populateDatasourceWithEntities("src/test/resources/data.txt");`
        
It's failing on not finding a suitable Datasource. 
`Unsatisfied dependency for type javax.sql.DataSource and qualifiers [@Default] `

**Comment by benstonezhang** [comment]
Here is part of my config for your reference.
```
quarkus.datasource.db-kind=mariadb
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3306/for_prod
quarkus.datasource.username=user_for_prod
quarkus.datasource.password=XXXXXXXXXXXXXXXXXXXXXXX
quarkus.hibernate-orm.database.generation=none

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:for_test;mode=mariadb;database_to_lower=true;case_insensitive_identifiers=true
%test.quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
%test.quarkus.hibernate-orm.database.generation=drop-and-create
```

**Comment by benstonezhang** [comment]
not a issue
